[package]
name = "jblock3d"
version = "0.1.0"
authors = ["Jacob Reckhard <jacobreckhard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.0"
rand = "*"
arr_macro = "0.1.3"
