[package]
name = "windowed_frontend"
version = "0.1.0"
authors = ["Arunscape <arun@woosaree.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.23.0"
log = "0.4.11"
simple_logger = "1.10.0"
